baseurl = "https://homedepot.github.io/opensource-corebeliefs/"
languageCode = "en-us"
title = "The Home Depot Open Source Office"
theme = "hugoscroll"

[params]
    description = "Open Source at The Home Depot"
